version: 2

build:
  image: latest

sphinx:
  configuration: documentation/source/conf.py
  fail_on_warning: true

python:
  version: 3.7
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs
